---
chdir: ./
rackup: ./config/rack/bunny_server.ru
environment: development
address: 0.0.0.0
timeout: 30
log: log/thin_production.log
pid: tmp/pids/thin_production.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: false
